// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// combinations_directed
arma::mat combinations_directed(unsigned int x);
RcppExport SEXP _redeem_combinations_directed(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(combinations_directed(x));
    return rcpp_result_gen;
END_RCPP
}
// combinations_undirected
arma::mat combinations_undirected(unsigned int x);
RcppExport SEXP _redeem_combinations_undirected(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(combinations_undirected(x));
    return rcpp_result_gen;
END_RCPP
}
// topk_indices
arma::uvec topk_indices(const arma::vec& x, arma::uword k);
RcppExport SEXP _redeem_topk_indices(SEXP xSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(topk_indices(x, k));
    return rcpp_result_gen;
END_RCPP
}
// do_call_full_cpp
arma::mat do_call_full_cpp(Rcpp::List res, double max_time);
RcppExport SEXP _redeem_do_call_full_cpp(SEXP resSEXP, SEXP max_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type res(resSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(do_call_full_cpp(res, max_time));
    return rcpp_result_gen;
END_RCPP
}
// preprocess
arma::mat preprocess(arma::mat edgelist, std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, bool simultaneous_interactions, Rcpp::Nullable<Rcpp::NumericVector> window_map, double build_time, double max_time);
RcppExport SEXP _redeem_preprocess(SEXP edgelistSEXP, SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP simultaneous_interactionsSEXP, SEXP window_mapSEXP, SEXP build_timeSEXP, SEXP max_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type edgelist(edgelistSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< bool >::type simultaneous_interactions(simultaneous_interactionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type window_map(window_mapSEXP);
    Rcpp::traits::input_parameter< double >::type build_time(build_timeSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocess(edgelist, terms, data_list, transformations, n_nodes, verbose, directed, simultaneous_interactions, window_map, build_time, max_time));
    return rcpp_result_gen;
END_RCPP
}
// preprocess_rem
arma::mat preprocess_rem(arma::mat edgelist, std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, Rcpp::Nullable<Rcpp::NumericVector> window_map, double build_time, double max_time);
RcppExport SEXP _redeem_preprocess_rem(SEXP edgelistSEXP, SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP window_mapSEXP, SEXP build_timeSEXP, SEXP max_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type edgelist(edgelistSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type window_map(window_mapSEXP);
    Rcpp::traits::input_parameter< double >::type build_time(build_timeSEXP);
    Rcpp::traits::input_parameter< double >::type max_time(max_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(preprocess_rem(edgelist, terms, data_list, transformations, n_nodes, verbose, directed, window_map, build_time, max_time));
    return rcpp_result_gen;
END_RCPP
}
// calc_llh_scaled
double calc_llh_scaled(Rcpp::NumericVector pred, Rcpp::NumericVector intensity, Rcpp::IntegerVector delta, Rcpp::IntegerVector pair_id);
RcppExport SEXP _redeem_calc_llh_scaled(SEXP predSEXP, SEXP intensitySEXP, SEXP deltaSEXP, SEXP pair_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pred(predSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type intensity(intensitySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type pair_id(pair_idSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_llh_scaled(pred, intensity, delta, pair_id));
    return rcpp_result_gen;
END_RCPP
}
// find_to
arma::uvec find_to(unsigned int to, bool directed, unsigned int n_nodes);
RcppExport SEXP _redeem_find_to(SEXP toSEXP, SEXP directedSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type to(toSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(find_to(to, directed, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// find_from
arma::uvec find_from(unsigned int from, bool directed, unsigned int n_nodes);
RcppExport SEXP _redeem_find_from(SEXP fromSEXP, SEXP directedSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type from(fromSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(find_from(from, directed, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// get_A_B_C_D_E_F_exact
Rcpp::List get_A_B_C_D_E_F_exact(const arma::vec& from_v, const arma::vec& to_v, const arma::vec& weight_v, const arma::mat& covarites, const arma::vec& time_slices, unsigned int n_slices, unsigned int n_nodes, bool directed, bool full_baseline);
RcppExport SEXP _redeem_get_A_B_C_D_E_F_exact(SEXP from_vSEXP, SEXP to_vSEXP, SEXP weight_vSEXP, SEXP covaritesSEXP, SEXP time_slicesSEXP, SEXP n_slicesSEXP, SEXP n_nodesSEXP, SEXP directedSEXP, SEXP full_baselineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type from_v(from_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type to_v(to_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight_v(weight_vSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type covarites(covaritesSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time_slices(time_slicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_slices(n_slicesSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< bool >::type full_baseline(full_baselineSEXP);
    rcpp_result_gen = Rcpp::wrap(get_A_B_C_D_E_F_exact(from_v, to_v, weight_v, covarites, time_slices, n_slices, n_nodes, directed, full_baseline));
    return rcpp_result_gen;
END_RCPP
}
// get_A_B_C_exact
Rcpp::List get_A_B_C_exact(const arma::mat& data, int n_nodes, bool directed);
RcppExport SEXP _redeem_get_A_B_C_exact(SEXP dataSEXP, SEXP n_nodesSEXP, SEXP directedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    rcpp_result_gen = Rcpp::wrap(get_A_B_C_exact(data, n_nodes, directed));
    return rcpp_result_gen;
END_RCPP
}
// get_data_degree
arma::mat get_data_degree(Rcpp::NumericVector from_v, Rcpp::NumericVector to_v, Rcpp::NumericVector obs_v, Rcpp::NumericVector pred_v, int n_nodes, bool directed);
RcppExport SEXP _redeem_get_data_degree(SEXP from_vSEXP, SEXP to_vSEXP, SEXP obs_vSEXP, SEXP pred_vSEXP, SEXP n_nodesSEXP, SEXP directedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type from_v(from_vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type to_v(to_vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type obs_v(obs_vSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pred_v(pred_vSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    rcpp_result_gen = Rcpp::wrap(get_data_degree(from_v, to_v, obs_v, pred_v, n_nodes, directed));
    return rcpp_result_gen;
END_RCPP
}
// get_data_time_alt
arma::mat get_data_time_alt(Rcpp::NumericVector slice_start_v_r, Rcpp::NumericVector slice_end_v_r, Rcpp::NumericVector time_start_v_r, Rcpp::NumericVector time_end_v_r, Rcpp::NumericVector weight_v_r, Rcpp::NumericVector observation_v_r, int n_slices, Rcpp::NumericVector changepoints_r, bool full_baseline);
RcppExport SEXP _redeem_get_data_time_alt(SEXP slice_start_v_rSEXP, SEXP slice_end_v_rSEXP, SEXP time_start_v_rSEXP, SEXP time_end_v_rSEXP, SEXP weight_v_rSEXP, SEXP observation_v_rSEXP, SEXP n_slicesSEXP, SEXP changepoints_rSEXP, SEXP full_baselineSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type slice_start_v_r(slice_start_v_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type slice_end_v_r(slice_end_v_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_start_v_r(time_start_v_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_end_v_r(time_end_v_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type weight_v_r(weight_v_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type observation_v_r(observation_v_rSEXP);
    Rcpp::traits::input_parameter< int >::type n_slices(n_slicesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type changepoints_r(changepoints_rSEXP);
    Rcpp::traits::input_parameter< bool >::type full_baseline(full_baselineSEXP);
    rcpp_result_gen = Rcpp::wrap(get_data_time_alt(slice_start_v_r, slice_end_v_r, time_start_v_r, time_end_v_r, weight_v_r, observation_v_r, n_slices, changepoints_r, full_baseline));
    return rcpp_result_gen;
END_RCPP
}
// integrate_step_function
double integrate_step_function(const arma::vec& change_points, const arma::vec& values, double from, double to, double from_slice, double to_slice);
RcppExport SEXP _redeem_integrate_step_function(SEXP change_pointsSEXP, SEXP valuesSEXP, SEXP fromSEXP, SEXP toSEXP, SEXP from_sliceSEXP, SEXP to_sliceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type change_points(change_pointsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< double >::type from(fromSEXP);
    Rcpp::traits::input_parameter< double >::type to(toSEXP);
    Rcpp::traits::input_parameter< double >::type from_slice(from_sliceSEXP);
    Rcpp::traits::input_parameter< double >::type to_slice(to_sliceSEXP);
    rcpp_result_gen = Rcpp::wrap(integrate_step_function(change_points, values, from, to, from_slice, to_slice));
    return rcpp_result_gen;
END_RCPP
}
// get_time_offset
arma::vec get_time_offset(Rcpp::NumericVector from_slice_r, Rcpp::NumericVector to_slice_r, Rcpp::NumericVector from_time_r, Rcpp::NumericVector to_time_r, Rcpp::NumericVector est_time_r, Rcpp::NumericVector changepoints_r);
RcppExport SEXP _redeem_get_time_offset(SEXP from_slice_rSEXP, SEXP to_slice_rSEXP, SEXP from_time_rSEXP, SEXP to_time_rSEXP, SEXP est_time_rSEXP, SEXP changepoints_rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type from_slice_r(from_slice_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type to_slice_r(to_slice_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type from_time_r(from_time_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type to_time_r(to_time_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type est_time_r(est_time_rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type changepoints_r(changepoints_rSEXP);
    rcpp_result_gen = Rcpp::wrap(get_time_offset(from_slice_r, to_slice_r, from_time_r, to_time_r, est_time_r, changepoints_r));
    return rcpp_result_gen;
END_RCPP
}
// update_degree_fast
Rcpp::List update_degree_fast(const arma::vec& from_v, const arma::vec& to_v, const arma::vec& event_v, const arma::vec& prediction_v, const arma::vec& weights, arma::vec est_degree, unsigned int n_nodes, bool directed, bool update_sender);
RcppExport SEXP _redeem_update_degree_fast(SEXP from_vSEXP, SEXP to_vSEXP, SEXP event_vSEXP, SEXP prediction_vSEXP, SEXP weightsSEXP, SEXP est_degreeSEXP, SEXP n_nodesSEXP, SEXP directedSEXP, SEXP update_senderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type from_v(from_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type to_v(to_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type event_v(event_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prediction_v(prediction_vSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type est_degree(est_degreeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< bool >::type update_sender(update_senderSEXP);
    rcpp_result_gen = Rcpp::wrap(update_degree_fast(from_v, to_v, event_v, prediction_v, weights, est_degree, n_nodes, directed, update_sender));
    return rcpp_result_gen;
END_RCPP
}
// update_degree_directed
arma::vec update_degree_directed(const arma::mat& update_data, const arma::vec& est_mu, const arma::vec& est_nu, int n_nodes);
RcppExport SEXP _redeem_update_degree_directed(SEXP update_dataSEXP, SEXP est_muSEXP, SEXP est_nuSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type update_data(update_dataSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type est_mu(est_muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type est_nu(est_nuSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(update_degree_directed(update_data, est_mu, est_nu, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// update_degree
arma::vec update_degree(const arma::mat& update_data, arma::vec& est_degree, int n_nodes, bool directed);
RcppExport SEXP _redeem_update_degree(SEXP update_dataSEXP, SEXP est_degreeSEXP, SEXP n_nodesSEXP, SEXP directedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type update_data(update_dataSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type est_degree(est_degreeSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    rcpp_result_gen = Rcpp::wrap(update_degree(update_data, est_degree, n_nodes, directed));
    return rcpp_result_gen;
END_RCPP
}
// eval_llh_pois
double eval_llh_pois(const arma::vec& outcome, const arma::vec& mean, const arma::vec& weights);
RcppExport SEXP _redeem_eval_llh_pois(SEXP outcomeSEXP, SEXP meanSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_llh_pois(outcome, mean, weights));
    return rcpp_result_gen;
END_RCPP
}
// eval_llh_pois_log
double eval_llh_pois_log(const arma::vec& outcome, const arma::vec& log_mean, const arma::vec& weights);
RcppExport SEXP _redeem_eval_llh_pois_log(SEXP outcomeSEXP, SEXP log_meanSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type log_mean(log_meanSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(eval_llh_pois_log(outcome, log_mean, weights));
    return rcpp_result_gen;
END_RCPP
}
// gd_step_halfing
arma::vec gd_step_halfing(const arma::mat& X, const arma::vec& y, const arma::vec& beta, const arma::vec& offset, double c);
RcppExport SEXP _redeem_gd_step_halfing(SEXP XSEXP, SEXP ySEXP, SEXP betaSEXP, SEXP offsetSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(gd_step_halfing(X, y, beta, offset, c));
    return rcpp_result_gen;
END_RCPP
}
// gd_estimation
Rcpp::List gd_estimation(const arma::mat& X, const arma::vec& y, const arma::vec& coef, const arma::vec& offset, const int& max_iter, double stepsize, const double& tol, double c);
RcppExport SEXP _redeem_gd_estimation(SEXP XSEXP, SEXP ySEXP, SEXP coefSEXP, SEXP offsetSEXP, SEXP max_iterSEXP, SEXP stepsizeSEXP, SEXP tolSEXP, SEXP cSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type stepsize(stepsizeSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    rcpp_result_gen = Rcpp::wrap(gd_estimation(X, y, coef, offset, max_iter, stepsize, tol, c));
    return rcpp_result_gen;
END_RCPP
}
// rem_simulate_from_empty_timevarying
Rcpp::List rem_simulate_from_empty_timevarying(unsigned int n_nodes, arma::vec coef, arma::vec degree_coef, arma::vec baseline, unsigned int n_events, unsigned int max_events, double time, arma::vec time_changepoints, std::vector<std::string> transformations, std::vector<std::string> terms, bool verbose, bool directed, Rcpp::List data_list, unsigned int seed, arma::vec block, Rcpp::List window_info);
RcppExport SEXP _redeem_rem_simulate_from_empty_timevarying(SEXP n_nodesSEXP, SEXP coefSEXP, SEXP degree_coefSEXP, SEXP baselineSEXP, SEXP n_eventsSEXP, SEXP max_eventsSEXP, SEXP timeSEXP, SEXP time_changepointsSEXP, SEXP transformationsSEXP, SEXP termsSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP data_listSEXP, SEXP seedSEXP, SEXP blockSEXP, SEXP window_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef(degree_coefSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline(baselineSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_events(n_eventsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_events(max_eventsSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_changepoints(time_changepointsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type block(blockSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type window_info(window_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(rem_simulate_from_empty_timevarying(n_nodes, coef, degree_coef, baseline, n_events, max_events, time, time_changepoints, transformations, terms, verbose, directed, data_list, seed, block, window_info));
    return rcpp_result_gen;
END_RCPP
}
// simulate_from_empty_timevarying
Rcpp::List simulate_from_empty_timevarying(std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, arma::vec coef_0_1, arma::vec coef_1_0, arma::vec degree_coef_0_1, arma::vec degree_coef_1_0, arma::vec time_changepoints, arma::vec baseline_0_1, arma::vec baseline_1_0, bool simultaneous_interactions, unsigned int n_events, unsigned int max_events, double time, Rcpp::List window_info, unsigned int seed);
RcppExport SEXP _redeem_simulate_from_empty_timevarying(SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP coef_0_1SEXP, SEXP coef_1_0SEXP, SEXP degree_coef_0_1SEXP, SEXP degree_coef_1_0SEXP, SEXP time_changepointsSEXP, SEXP baseline_0_1SEXP, SEXP baseline_1_0SEXP, SEXP simultaneous_interactionsSEXP, SEXP n_eventsSEXP, SEXP max_eventsSEXP, SEXP timeSEXP, SEXP window_infoSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_0_1(coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_1_0(coef_1_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_0_1(degree_coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_1_0(degree_coef_1_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type time_changepoints(time_changepointsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_0_1(baseline_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type baseline_1_0(baseline_1_0SEXP);
    Rcpp::traits::input_parameter< bool >::type simultaneous_interactions(simultaneous_interactionsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_events(n_eventsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_events(max_eventsSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type window_info(window_infoSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_from_empty_timevarying(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, time_changepoints, baseline_0_1, baseline_1_0, simultaneous_interactions, n_events, max_events, time, window_info, seed));
    return rcpp_result_gen;
END_RCPP
}
// rem_simulate_from_empty
arma::mat rem_simulate_from_empty(std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, arma::vec coef, arma::vec degree_coef, unsigned int n_events, double time, unsigned int max_events, arma::vec block, Rcpp::List window_info, unsigned int seed);
RcppExport SEXP _redeem_rem_simulate_from_empty(SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP coefSEXP, SEXP degree_coefSEXP, SEXP n_eventsSEXP, SEXP timeSEXP, SEXP max_eventsSEXP, SEXP blockSEXP, SEXP window_infoSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef(coefSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef(degree_coefSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_events(n_eventsSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_events(max_eventsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type block(blockSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type window_info(window_infoSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(rem_simulate_from_empty(terms, data_list, transformations, n_nodes, verbose, directed, coef, degree_coef, n_events, time, max_events, block, window_info, seed));
    return rcpp_result_gen;
END_RCPP
}
// simulate_from_empty
arma::mat simulate_from_empty(std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, arma::vec coef_0_1, arma::vec coef_1_0, arma::vec degree_coef_0_1, arma::vec degree_coef_1_0, unsigned int n_events, double time, unsigned int max_events, bool simultaneous_interactions, Rcpp::List window_info, unsigned int seed);
RcppExport SEXP _redeem_simulate_from_empty(SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP coef_0_1SEXP, SEXP coef_1_0SEXP, SEXP degree_coef_0_1SEXP, SEXP degree_coef_1_0SEXP, SEXP n_eventsSEXP, SEXP timeSEXP, SEXP max_eventsSEXP, SEXP simultaneous_interactionsSEXP, SEXP window_infoSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_0_1(coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_1_0(coef_1_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_0_1(degree_coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_1_0(degree_coef_1_0SEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_events(n_eventsSEXP);
    Rcpp::traits::input_parameter< double >::type time(timeSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type max_events(max_eventsSEXP);
    Rcpp::traits::input_parameter< bool >::type simultaneous_interactions(simultaneous_interactionsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type window_info(window_infoSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_from_empty(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, n_events, time, max_events, simultaneous_interactions, window_info, seed));
    return rcpp_result_gen;
END_RCPP
}
// get_probabilities_per_test_event
Rcpp::List get_probabilities_per_test_event(std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, arma::vec coef_0_1, arma::vec coef_1_0, arma::vec degree_coef_0_1, arma::vec degree_coef_1_0, bool simultaneous_interactions, arma::mat edgelist_train, arma::mat edgelist_test, unsigned int k, bool is_rem, Rcpp::List window_info, Rcpp::Nullable<Rcpp::NumericVector> baseline_0_1, Rcpp::Nullable<Rcpp::NumericVector> baseline_1_0);
RcppExport SEXP _redeem_get_probabilities_per_test_event(SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP coef_0_1SEXP, SEXP coef_1_0SEXP, SEXP degree_coef_0_1SEXP, SEXP degree_coef_1_0SEXP, SEXP simultaneous_interactionsSEXP, SEXP edgelist_trainSEXP, SEXP edgelist_testSEXP, SEXP kSEXP, SEXP is_remSEXP, SEXP window_infoSEXP, SEXP baseline_0_1SEXP, SEXP baseline_1_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_0_1(coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_1_0(coef_1_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_0_1(degree_coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_1_0(degree_coef_1_0SEXP);
    Rcpp::traits::input_parameter< bool >::type simultaneous_interactions(simultaneous_interactionsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type edgelist_train(edgelist_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type edgelist_test(edgelist_testSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type k(kSEXP);
    Rcpp::traits::input_parameter< bool >::type is_rem(is_remSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type window_info(window_infoSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type baseline_0_1(baseline_0_1SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type baseline_1_0(baseline_1_0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_probabilities_per_test_event(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, simultaneous_interactions, edgelist_train, edgelist_test, k, is_rem, window_info, baseline_0_1, baseline_1_0));
    return rcpp_result_gen;
END_RCPP
}
// get_oos_likelihood_cpp
arma::vec get_oos_likelihood_cpp(std::vector<std::string> terms, Rcpp::List data_list, std::vector<std::string> transformations, unsigned int n_nodes, bool verbose, bool directed, arma::vec coef_0_1, arma::vec coef_1_0, arma::vec degree_coef_0_1, arma::vec degree_coef_1_0, bool simultaneous_interactions, arma::mat edgelist_train, arma::mat edgelist_test, bool is_rem, Rcpp::List window_info, Rcpp::Nullable<Rcpp::NumericVector> baseline_0_1, Rcpp::Nullable<Rcpp::NumericVector> baseline_1_0);
RcppExport SEXP _redeem_get_oos_likelihood_cpp(SEXP termsSEXP, SEXP data_listSEXP, SEXP transformationsSEXP, SEXP n_nodesSEXP, SEXP verboseSEXP, SEXP directedSEXP, SEXP coef_0_1SEXP, SEXP coef_1_0SEXP, SEXP degree_coef_0_1SEXP, SEXP degree_coef_1_0SEXP, SEXP simultaneous_interactionsSEXP, SEXP edgelist_trainSEXP, SEXP edgelist_testSEXP, SEXP is_remSEXP, SEXP window_infoSEXP, SEXP baseline_0_1SEXP, SEXP baseline_1_0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type terms(termsSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type data_list(data_listSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type transformations(transformationsSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type directed(directedSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_0_1(coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type coef_1_0(coef_1_0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_0_1(degree_coef_0_1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type degree_coef_1_0(degree_coef_1_0SEXP);
    Rcpp::traits::input_parameter< bool >::type simultaneous_interactions(simultaneous_interactionsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type edgelist_train(edgelist_trainSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type edgelist_test(edgelist_testSEXP);
    Rcpp::traits::input_parameter< bool >::type is_rem(is_remSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type window_info(window_infoSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type baseline_0_1(baseline_0_1SEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type baseline_1_0(baseline_1_0SEXP);
    rcpp_result_gen = Rcpp::wrap(get_oos_likelihood_cpp(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, simultaneous_interactions, edgelist_train, edgelist_test, is_rem, window_info, baseline_0_1, baseline_1_0));
    return rcpp_result_gen;
END_RCPP
}
// update_core_cpp
arma::vec update_core_cpp(const arma::mat& X, const arma::vec& y, const arma::vec& prediction, arma::vec est_core, const arma::uvec& identifiable, const arma::vec& offset_fixed, const arma::vec& weights);
RcppExport SEXP _redeem_update_core_cpp(SEXP XSEXP, SEXP ySEXP, SEXP predictionSEXP, SEXP est_coreSEXP, SEXP identifiableSEXP, SEXP offset_fixedSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type prediction(predictionSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type est_core(est_coreSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type identifiable(identifiableSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type offset_fixed(offset_fixedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(update_core_cpp(X, y, prediction, est_core, identifiable, offset_fixed, weights));
    return rcpp_result_gen;
END_RCPP
}
// get_union_bounds
Rcpp::DataFrame get_union_bounds(Rcpp::IntegerVector pair_id, Rcpp::NumericVector time_start, Rcpp::NumericVector time_end);
RcppExport SEXP _redeem_get_union_bounds(SEXP pair_idSEXP, SEXP time_startSEXP, SEXP time_endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type pair_id(pair_idSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_start(time_startSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type time_end(time_endSEXP);
    rcpp_result_gen = Rcpp::wrap(get_union_bounds(pair_id, time_start, time_end));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_redeem_combinations_directed", (DL_FUNC) &_redeem_combinations_directed, 1},
    {"_redeem_combinations_undirected", (DL_FUNC) &_redeem_combinations_undirected, 1},
    {"_redeem_topk_indices", (DL_FUNC) &_redeem_topk_indices, 2},
    {"_redeem_do_call_full_cpp", (DL_FUNC) &_redeem_do_call_full_cpp, 2},
    {"_redeem_preprocess", (DL_FUNC) &_redeem_preprocess, 11},
    {"_redeem_preprocess_rem", (DL_FUNC) &_redeem_preprocess_rem, 10},
    {"_redeem_calc_llh_scaled", (DL_FUNC) &_redeem_calc_llh_scaled, 4},
    {"_redeem_find_to", (DL_FUNC) &_redeem_find_to, 3},
    {"_redeem_find_from", (DL_FUNC) &_redeem_find_from, 3},
    {"_redeem_get_A_B_C_D_E_F_exact", (DL_FUNC) &_redeem_get_A_B_C_D_E_F_exact, 9},
    {"_redeem_get_A_B_C_exact", (DL_FUNC) &_redeem_get_A_B_C_exact, 3},
    {"_redeem_get_data_degree", (DL_FUNC) &_redeem_get_data_degree, 6},
    {"_redeem_get_data_time_alt", (DL_FUNC) &_redeem_get_data_time_alt, 9},
    {"_redeem_integrate_step_function", (DL_FUNC) &_redeem_integrate_step_function, 6},
    {"_redeem_get_time_offset", (DL_FUNC) &_redeem_get_time_offset, 6},
    {"_redeem_update_degree_fast", (DL_FUNC) &_redeem_update_degree_fast, 9},
    {"_redeem_update_degree_directed", (DL_FUNC) &_redeem_update_degree_directed, 4},
    {"_redeem_update_degree", (DL_FUNC) &_redeem_update_degree, 4},
    {"_redeem_eval_llh_pois", (DL_FUNC) &_redeem_eval_llh_pois, 3},
    {"_redeem_eval_llh_pois_log", (DL_FUNC) &_redeem_eval_llh_pois_log, 3},
    {"_redeem_gd_step_halfing", (DL_FUNC) &_redeem_gd_step_halfing, 5},
    {"_redeem_gd_estimation", (DL_FUNC) &_redeem_gd_estimation, 8},
    {"_redeem_rem_simulate_from_empty_timevarying", (DL_FUNC) &_redeem_rem_simulate_from_empty_timevarying, 16},
    {"_redeem_simulate_from_empty_timevarying", (DL_FUNC) &_redeem_simulate_from_empty_timevarying, 19},
    {"_redeem_rem_simulate_from_empty", (DL_FUNC) &_redeem_rem_simulate_from_empty, 14},
    {"_redeem_simulate_from_empty", (DL_FUNC) &_redeem_simulate_from_empty, 16},
    {"_redeem_get_probabilities_per_test_event", (DL_FUNC) &_redeem_get_probabilities_per_test_event, 18},
    {"_redeem_get_oos_likelihood_cpp", (DL_FUNC) &_redeem_get_oos_likelihood_cpp, 17},
    {"_redeem_update_core_cpp", (DL_FUNC) &_redeem_update_core_cpp, 7},
    {"_redeem_get_union_bounds", (DL_FUNC) &_redeem_get_union_bounds, 3},
    {NULL, NULL, 0}
};

void redeem_init_callable(DllInfo *dll);
RcppExport void R_init_redeem(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    redeem_init_callable(dll);
}
