# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combinations_directed <- function(x) {
    .Call(`_redeem_combinations_directed`, x)
}

combinations_undirected <- function(x) {
    .Call(`_redeem_combinations_undirected`, x)
}

topk_indices <- function(x, k) {
    .Call(`_redeem_topk_indices`, x, k)
}

do_call_full_cpp <- function(res, max_time) {
    .Call(`_redeem_do_call_full_cpp`, res, max_time)
}

preprocess <- function(edgelist, terms, data_list, transformations, n_nodes, verbose, directed, simultaneous_interactions, window_map = NULL, build_time = 0.0, max_time = 0.0) {
    .Call(`_redeem_preprocess`, edgelist, terms, data_list, transformations, n_nodes, verbose, directed, simultaneous_interactions, window_map, build_time, max_time)
}

preprocess_rem <- function(edgelist, terms, data_list, transformations, n_nodes, verbose, directed, window_map = NULL, build_time = 0.0, max_time = 0.0) {
    .Call(`_redeem_preprocess_rem`, edgelist, terms, data_list, transformations, n_nodes, verbose, directed, window_map, build_time, max_time)
}

calc_llh_scaled <- function(pred, intensity, delta, pair_id) {
    .Call(`_redeem_calc_llh_scaled`, pred, intensity, delta, pair_id)
}

find_to <- function(to, directed, n_nodes) {
    .Call(`_redeem_find_to`, to, directed, n_nodes)
}

find_from <- function(from, directed, n_nodes) {
    .Call(`_redeem_find_from`, from, directed, n_nodes)
}

get_A_B_C_D_E_F_exact <- function(from_v, to_v, weight_v, covarites, time_slices, n_slices, n_nodes, directed, full_baseline = FALSE) {
    .Call(`_redeem_get_A_B_C_D_E_F_exact`, from_v, to_v, weight_v, covarites, time_slices, n_slices, n_nodes, directed, full_baseline)
}

get_A_B_C_exact <- function(data, n_nodes, directed) {
    .Call(`_redeem_get_A_B_C_exact`, data, n_nodes, directed)
}

get_data_degree <- function(from_v, to_v, obs_v, pred_v, n_nodes, directed) {
    .Call(`_redeem_get_data_degree`, from_v, to_v, obs_v, pred_v, n_nodes, directed)
}

get_data_time_alt <- function(slice_start_v_r, slice_end_v_r, time_start_v_r, time_end_v_r, weight_v_r, observation_v_r, n_slices, changepoints_r, full_baseline = FALSE) {
    .Call(`_redeem_get_data_time_alt`, slice_start_v_r, slice_end_v_r, time_start_v_r, time_end_v_r, weight_v_r, observation_v_r, n_slices, changepoints_r, full_baseline)
}

integrate_step_function <- function(change_points, values, from, to, from_slice, to_slice) {
    .Call(`_redeem_integrate_step_function`, change_points, values, from, to, from_slice, to_slice)
}

get_time_offset <- function(from_slice_r, to_slice_r, from_time_r, to_time_r, est_time_r, changepoints_r) {
    .Call(`_redeem_get_time_offset`, from_slice_r, to_slice_r, from_time_r, to_time_r, est_time_r, changepoints_r)
}

update_degree_fast <- function(from_v, to_v, event_v, prediction_v, weights, est_degree, n_nodes, directed, update_sender = TRUE) {
    .Call(`_redeem_update_degree_fast`, from_v, to_v, event_v, prediction_v, weights, est_degree, n_nodes, directed, update_sender)
}

update_degree_directed <- function(update_data, est_mu, est_nu, n_nodes) {
    .Call(`_redeem_update_degree_directed`, update_data, est_mu, est_nu, n_nodes)
}

update_degree <- function(update_data, est_degree, n_nodes, directed) {
    .Call(`_redeem_update_degree`, update_data, est_degree, n_nodes, directed)
}

eval_llh_pois <- function(outcome, mean, weights) {
    .Call(`_redeem_eval_llh_pois`, outcome, mean, weights)
}

eval_llh_pois_log <- function(outcome, log_mean, weights) {
    .Call(`_redeem_eval_llh_pois_log`, outcome, log_mean, weights)
}

gd_step_halfing <- function(X, y, beta, offset, c) {
    .Call(`_redeem_gd_step_halfing`, X, y, beta, offset, c)
}

gd_estimation <- function(X, y, coef, offset, max_iter = 1000L, stepsize = 10.0, tol = 0.001, c = 0.001) {
    .Call(`_redeem_gd_estimation`, X, y, coef, offset, max_iter, stepsize, tol, c)
}

rem_simulate_from_empty_timevarying <- function(n_nodes, coef, degree_coef, baseline, n_events, max_events, time, time_changepoints, transformations, terms, verbose, directed, data_list, seed, block, window_info) {
    .Call(`_redeem_rem_simulate_from_empty_timevarying`, n_nodes, coef, degree_coef, baseline, n_events, max_events, time, time_changepoints, transformations, terms, verbose, directed, data_list, seed, block, window_info)
}

simulate_from_empty_timevarying <- function(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, time_changepoints, baseline_0_1, baseline_1_0, simultaneous_interactions, n_events, max_events, time, window_info, seed = 0L) {
    .Call(`_redeem_simulate_from_empty_timevarying`, terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, time_changepoints, baseline_0_1, baseline_1_0, simultaneous_interactions, n_events, max_events, time, window_info, seed)
}

rem_simulate_from_empty <- function(terms, data_list, transformations, n_nodes, verbose, directed, coef, degree_coef, n_events, time, max_events, block, window_info, seed = 0L) {
    .Call(`_redeem_rem_simulate_from_empty`, terms, data_list, transformations, n_nodes, verbose, directed, coef, degree_coef, n_events, time, max_events, block, window_info, seed)
}

simulate_from_empty <- function(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, n_events, time, max_events, simultaneous_interactions, window_info, seed = 0L) {
    .Call(`_redeem_simulate_from_empty`, terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, n_events, time, max_events, simultaneous_interactions, window_info, seed)
}

get_probabilities_per_test_event <- function(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, simultaneous_interactions, edgelist_train, edgelist_test, k, is_rem, window_info, baseline_0_1 = NULL, baseline_1_0 = NULL) {
    .Call(`_redeem_get_probabilities_per_test_event`, terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, simultaneous_interactions, edgelist_train, edgelist_test, k, is_rem, window_info, baseline_0_1, baseline_1_0)
}

get_oos_likelihood_cpp <- function(terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, simultaneous_interactions, edgelist_train, edgelist_test, is_rem, window_info, baseline_0_1 = NULL, baseline_1_0 = NULL) {
    .Call(`_redeem_get_oos_likelihood_cpp`, terms, data_list, transformations, n_nodes, verbose, directed, coef_0_1, coef_1_0, degree_coef_0_1, degree_coef_1_0, simultaneous_interactions, edgelist_train, edgelist_test, is_rem, window_info, baseline_0_1, baseline_1_0)
}

update_core_cpp <- function(X, y, prediction, est_core, identifiable, offset_fixed, weights) {
    .Call(`_redeem_update_core_cpp`, X, y, prediction, est_core, identifiable, offset_fixed, weights)
}

get_union_bounds <- function(pair_id, time_start, time_end) {
    .Call(`_redeem_get_union_bounds`, pair_id, time_start, time_end)
}

